### PR TITLE
Blob cast leads to bad performance

### PR DESCRIPTION
**Pull request by Dabbel**

### CODE REVIEW

**Comment by cincuranet** [comment]
Can you add some tests for it? I'm not convinced it's correct.

**Comment by Dabbel** [comment]
Both is not really correct. The problem with cast to 'blob subtype text' is, the query gets very slow.

This is the lambda expression that encounters the problem.

```
var compareValue = "Test";

m => m.StringField.StartsWith(compareValue)
```

The cast isn't generated on the datatype of the database field nor on the length of the compareValue. It will be casted to 'blob subtype text' even if the length of the compareValue is smaller as the datatype length.
In the EF6 provider the cast is correct, it will be casted to varchar.

Would it be okay for you if i change the code that i only do the cast to varchar if the length of the compareValue doesn't exceeds the max length of varchar for firebird?
In my opinion this would be the correct solution.

**Comment by Dabbel** [comment]
I have added an option that everyone can decide on its own if he wants a blod or varchar cast

**Comment by cincuranet** [comment]
What you're probably looking for is `WithExplicitParameterTypes` in `UseFirebird`.

On the other hand, I'd like to know more about the "_if the length of the compareValue_". AFAIK you don't know the length in mapping. You only know the length in i.e. SQL generation, but that's a wrong place to do such decision.

**Comment by Dabbel** [comment]
The type cast is ommited with `WithExplicitParameterTypes(false)` but now lambda expressions with "StartsWith" throws an exception

```
Dynamic SQL Error
SQL error code = -804
Data type unknown
```

The type cast for "StartsWith" is required but if it is casted to "blob subtype text" the query gets very slow.

In my opinion the solution with the option fits best for all cases. Everyone can decide on its own if he wants a "blob subtype text" or "varchar" cast.

With _"if the length of the compareValue"_ i only mean that in the EF6 provider it is a varchar not a "blob subtype text" cast.

**Comment by cincuranet** [comment]
> The type cast is ommited with WithExplicitParameterTypes(false) but now lambda expressions with "StartsWith" throws an exception

Yes, that's why the option is there. Firebird does not handle parameters "left" side.

> In my opinion the solution with the option fits best for all cases. Everyone can decide on its own if he wants a "blob subtype text" or "varchar" cast.

Not correct. The type mapper is used in various places and your option is global and affects other mappings.

Don't get me wrong, this is a good catch, but I'd like to find proper solution.

> With "if the length of the compareValue" i only mean that in the EF6 provider it is a varchar not a "blob subtype text" cast.

I didn't get that initially. Also EF6 has different architecture, so comparing these two is pointless.

**Comment by Dabbel** [comment]
> > In my opinion the solution with the option fits best for all cases. Everyone can decide on its own if he wants a "blob subtype text" or "varchar" cast.
> 
> Not correct. The type mapper is used in various places and your option is global and affects other mappings.

I didn't know that the type mapper is used in various places. I'm new to writing ef providers.

> Don't get me wrong, this is a good catch, but I'd like to find proper solution.

I don't get you wrong. From your post before you said the `FbQuerySqlGenerator` would be the wrong place for that. Could it be that the proper solution would be an implementation like the `FbStringSubstringTranslator`? If so i could try to implement it that way.

> 
> > With "if the length of the compareValue" i only mean that in the EF6 provider it is a varchar not a "blob subtype text" cast.
> 
> I didn't get that initially. Also EF6 has different architecture, so comparing these two is pointless.

I know they have different architecture, but the generated sql query should be the same.

Our problem with the blob cast is that the query takes about 2 seconds and before it returned in nearly 100 milliseconds

**Comment by cincuranet** [comment]
> I don't get you wrong. From your post before you said the FbQuerySqlGenerator would be the wrong place for that. Could it be that the proper solution would be an implementation like the FbStringSubstringTranslator? If so i could try to implement it that way.

That's probably a way to go. But it's going to be heavy-duty expression visitor, which sucks too. I'm, at the moment, even thinking about simple branching for `ParameterExpression` for _clob_ values and converting that to _varchar_, which would be simple enough and still acceptable (given there's also `WithExplicitParameterTypes`).

**Comment by cincuranet** [comment]
Thinking about it bit more. The correct approach would be to detect where the cast is needed and do it. But that's not an easy task to do. As a intermediate thing, I guess blindly casting to `VARCHAR(8191)` seems to be viable solution. Yes, it will fail for blob strings longer than that, but I guess that's usually not common in selects (and I do that already for constants anyway). I'll whip of some code and let's see.

**Comment by Dabbel** [comment]
If i got it right now you will do the changes on your own in the master branch?

**Comment by cincuranet** [comment]
Yeah, I'll try. At the moment playing in [this branch](https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/compare/string-params). Feel free to discuss.

**Comment by Dabbel** [comment]
I would add a string argument to `StringParameterQueryType` and in `FbQuerySqlGenerator` use `ParameterValues[parameterExpression.Name] as string` as argument.
In `FbTypeMappingSource` i would check if the argument is `null` then use `VARCHAR({VarcharMaxSize})` otherwise `VARCHAR({argument.Length})`, this could be a better memory usage for the database.

The cast to `IFbTypeMappingSource` always works, right?

For me it looks good.

**Comment by cincuranet** [comment]
> I would add a string argument to StringParameterQueryType and in FbQuerySqlGenerator use ParameterValues[parameterExpression.Name] as string as argument.
In FbTypeMappingSource i would check if the argument is null then use VARCHAR({VarcharMaxSize}) otherwise VARCHAR({argument.Length}), this could be a better memory usage for the database.

For `NULL` `VARCHAR(1)` is probably enough. Also the `IsCacheable` needs to be handled in this case, because as the parameters might get different values, query needs to differ.

What I'm thinking about is whether every string should end up in `VARCHAR` or whether I should check for fixed length strings first and then leave `CHAR` there. 

> The cast to IFbTypeMappingSource always works, right?

In stock implementation, yes.

**Comment by cincuranet** [comment]
Ahh, silly me. For parameter we're operating on the _type_ and not something like `IProperty`, so `CHAR` is out of question.

So it looks like it's done. When [this](https://dev.azure.com/FirebirdClient/CI/_build/results?buildId=1173) build finishes, you can give it a try.

**Comment by Dabbel** [comment]
> So it looks like it's done. When [this](https://dev.azure.com/FirebirdClient/CI/_build/results?buildId=1173) build finishes, you can give it a try.

Great, but silly question, where do i find the NuGet Packages?

**Comment by Dabbel** [comment]
Found the packages and one bug.

In `FbTypeMappingSource` method `StringLiteralQueryType` and `StringParameterQueryType`. 

If `s` is zero length cast would be `VARCHAR(0)` and fails. Min length should be 1.

**Comment by cincuranet** [comment]
That's already fixed in the same branch in further commits.

**Comment by cincuranet** [comment]
Done in efc5203.

**Comment by Dabbel** [comment]
Great and thx for the fast help. You already have an ETA for the release?

**Comment by cincuranet** [comment]
No ETA at the moment.

**Pull request closed without merging**
